import type {
  BOMPart,
  CADFile,
  ChangeRequest,
  ApprovalStep,
  PLMStatItem,
} from "@/components/plm";
import {
  Box,
  Layers,
  File as FileIcon,
  GitPullRequest,
  Truck,
} from "lucide-react";

// Mock BOM Parts Data
export const mockBOMParts: BOMPart[] = [
  {
    id: "1",
    level: 1,
    partNumber: "ECU-001",
    name: "Main Control Unit",
    quantity: 1,
    unit: "EA",
    revision: "v2.1",
    status: "released",
    expandable: true,
    children: [
      {
        id: "2",
        level: 2,
        partNumber: "PCB-101",
        name: "Main PCB Assembly",
        quantity: 1,
        unit: "EA",
        revision: "v1.3",
        status: "released",
        indent: 1,
        expandable: true,
        children: [
          {
            id: "3",
            level: 3,
            partNumber: "IC-501",
            name: "MCU Controller",
            quantity: 1,
            unit: "EA",
            revision: "v2.0",
            status: "released",
            indent: 2,
            supplier: "Texas Instruments",
          },
          {
            id: "4",
            level: 3,
            partNumber: "CAP-201",
            name: "Ceramic Capacitor 10uF",
            quantity: 12,
            unit: "EA",
            revision: "v1.0",
            status: "approved",
            indent: 2,
            supplier: "Murata",
          },
          {
            id: "5",
            level: 3,
            partNumber: "RES-301",
            name: "Surface Mount Resistor 10K",
            quantity: 24,
            unit: "EA",
            revision: "v1.0",
            status: "released",
            indent: 2,
            supplier: "Yageo",
          },
        ],
      },
      {
        id: "6",
        level: 2,
        partNumber: "CASE-301",
        name: "Aluminum Housing",
        quantity: 1,
        unit: "EA",
        revision: "v1.1",
        status: "released",
        indent: 1,
        supplier: "Custom Parts Inc.",
      },
      {
        id: "7",
        level: 2,
        partNumber: "CONN-401",
        name: "Header Connector 32-pin",
        quantity: 2,
        unit: "EA",
        revision: "v1.2",
        status: "approved",
        indent: 1,
        supplier: "Molex",
      },
    ],
  },
  {
    id: "8",
    level: 1,
    partNumber: "PWR-002",
    name: "Power Supply Module",
    quantity: 1,
    unit: "EA",
    revision: "v1.5",
    status: "released",
    expandable: true,
    children: [
      {
        id: "9",
        level: 2,
        partNumber: "XFR-101",
        name: "Power Transformer 12V",
        quantity: 1,
        unit: "EA",
        revision: "v1.0",
        status: "released",
        indent: 1,
        supplier: "TDK",
      },
      {
        id: "10",
        level: 2,
        partNumber: "REG-201",
        name: "Voltage Regulator",
        quantity: 1,
        unit: "EA",
        revision: "v2.1",
        status: "pending",
        indent: 1,
        supplier: "Infineon",
      },
    ],
  },
  {
    id: "11",
    level: 1,
    partNumber: "SENS-003",
    name: "Sensor Array",
    quantity: 1,
    unit: "EA",
    revision: "v1.0",
    status: "draft",
    expandable: false,
  },
];

// Mock CAD Files Data
export const mockCADFiles: CADFile[] = [
  {
    id: "1",
    name: "ecu_assembly_v2.1.dwg",
    type: "cad",
    size: "2.4 MB",
    modified: "2 hours ago",
    thumbnail: true,
  },
  {
    id: "2",
    name: "pcb_layout_v1.3.brd",
    type: "pcb",
    size: "890 KB",
    modified: "1 day ago",
    thumbnail: true,
  },
  {
    id: "3",
    name: "housing_v1.1.step",
    type: "3d",
    size: "1.2 MB",
    modified: "3 days ago",
    thumbnail: true,
  },
  {
    id: "4",
    name: "connector_32pin.3dxml",
    type: "3d",
    size: "450 KB",
    modified: "1 week ago",
    thumbnail: true,
  },
  {
    id: "5",
    name: "power_schematic.pdf",
    type: "pdf",
    size: "1.8 MB",
    modified: "2 weeks ago",
    thumbnail: false,
  },
];

// Mock Change Requests Data
export const mockChangeRequests: ChangeRequest[] = [
  {
    id: "ECR-2024-015",
    type: "ECR",
    title: "Update MCU to latest revision",
    status: "pending",
    createdAt: "2024-03-18",
    createdBy: "John Doe",
  },
  {
    id: "ECO-2024-012",
    type: "ECO",
    title: "Capacitor value change",
    status: "implemented",
    createdAt: "2024-03-15",
    createdBy: "Sarah Kim",
  },
  {
    id: "ECN-2024-008",
    type: "ECN",
    title: "Housing material update",
    status: "released",
    createdAt: "2024-03-10",
    createdBy: "Anna Lee",
  },
  {
    id: "ECR-2024-014",
    type: "ECR",
    title: "Add thermal protection circuit",
    status: "approved",
    createdAt: "2024-03-08",
    createdBy: "Robert Kim",
  },
];

// Mock Approval Timeline Data
export const mockApprovalSteps: ApprovalStep[] = [
  {
    id: "1",
    name: "Design Review",
    status: "completed",
    date: "2024-03-15",
    approver: "John Doe",
    avatar: "JD",
    comments: "Design approved with minor suggestions",
  },
  {
    id: "2",
    name: "Engineering Approval",
    status: "completed",
    date: "2024-03-20",
    approver: "Sarah Kim",
    avatar: "SK",
    comments: "All engineering requirements met",
  },
  {
    id: "3",
    name: "Quality Check",
    status: "in-progress",
    approver: "Anna Lee",
    avatar: "AL",
  },
  {
    id: "4",
    name: "Production Release",
    status: "pending",
    approver: "Robert Kim",
    avatar: "RK",
  },
];

// Mock PLM Stats Data
export const mockPLMStats: PLMStatItem[] = [
  {
    icon: Box,
    iconColor: "#3b82f6",
    value: "847",
    label: "Total Parts",
  },
  {
    icon: Layers,
    iconColor: "#8b5cf6",
    value: "12",
    label: "Active BOMs",
  },
  {
    icon: FileIcon,
    iconColor: "#f59e0b",
    value: "234",
    label: "CAD Files",
  },
  {
    icon: GitPullRequest,
    iconColor: "#ef4444",
    value: "8",
    label: "Pending ECRs",
  },
  {
    icon: Truck,
    iconColor: "#22c55e",
    value: "45",
    label: "Suppliers",
  },
];

// Mock BOM Filters
export const mockBOMFilters = [
  { label: "All", value: "all", active: true },
  { label: "Electrical", value: "electrical", active: false },
  { label: "Mechanical", value: "mechanical", active: false },
  { label: "Software", value: "software", active: false },
];
